<a href="https://colab.research.google.com/github/CharlesXace/js/blob/main/chapter_appendix-tools-for-deep-learning/jupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available.Using CPU")

# Creating a Tensor


In [ ]:
#using empty
a=torch.empty(2,3)
print(a)

In [8]:
#check type
type(a)

torch.Tensor

In [9]:
#using zeros
b=torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
#using rand (random between 0 to 1)
torch.rand(2,3)

tensor([[0.1723, 0.2704, 0.5821],
        [0.8173, 0.0259, 0.4445]])

In [12]:
#using manual seed (to not change value at evry rand call)
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# other ways

# arange (range)
print("using arange ->", torch.arange(0,10))
print("using arange ->", torch.arange(0,10,2))


# using linspace (linear space from 0 to 10 with 10 elements)
print("using linspace ->", torch.linspace(0,10,10))

# using eye (identity matrix)
print("using eye ->", torch.eye(5))

# using full (3x3 matrix with all elements 5)
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [15]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
#create a tensor with same size
torch.empty_like(x)

tensor([[ 680608870739572833,         49157242880, 7306355942478653766],
        [8214565720532602480,      85152021610498, 1452692354813686272]])

In [19]:
#create ones or zeroes tensor of same size
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [32]:
#create rand with mentioned datatype
a=torch.rand_like(x, dtype=torch.float32)
print(a)
b=torch.rand_like(x, dtype=torch.float64)
print(b)

tensor([[0.6211, 0.5530, 0.6896],
        [0.3687, 0.9053, 0.8356]])
tensor([[0.4312, 0.5917, 0.3425],
        [0.2202, 0.7030, 0.5629]], dtype=torch.float64)


# Tensor Datatypes


In [20]:
#find data type
x.dtype

torch.int64

In [21]:
#assign datatype
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
#using to()
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations

1. Scalar Operation

In [33]:
x=torch.rand(2,3)
x

tensor([[0.1157, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [34]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division (//)
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[2.1157, 2.6574, 2.3451],
        [2.0453, 2.9798, 2.5548]])

2. Element Wise Operation

In [36]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.6868, 0.4920, 0.0748],
        [0.9605, 0.3271, 0.0103]])
tensor([[0.9516, 0.2855, 0.2324],
        [0.9141, 0.7668, 0.1659]])


In [37]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.6868, 0.2065, 0.0748],
        [0.0464, 0.3271, 0.0103]])

In [38]:
c = torch.tensor([1, -2, 3, -4])

In [41]:
# abs (absolute value)
torch.abs(c)
# neg
torch.neg(c)

tensor([-1,  2, -3,  4])

In [42]:
d=torch.tensor([1.9,2.3,3.7,4.4])
#round
#ceil
#floor

In [43]:
#clamp (clamp in range)
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction Operation

In [44]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 5., 4.],
        [4., 1., 1.]])

In [45]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([10.,  6.])

In [46]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([2.5000, 3.0000, 2.5000])

In [47]:
# median
torch.median(e)

tensor(1.)

In [48]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [49]:
# product
torch.prod(e)

tensor(80.)

In [51]:
# standard deviation
torch.std(e)
# variance
torch.var(e)

tensor(3.4667)

In [53]:
# argmax (position of largest element)
torch.argmax(e)
# argmin
torch.argmin(e)

tensor(0)

4. Matrix Operations

In [54]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 4, 7],
        [2, 5, 6]])
tensor([[1, 4],
        [5, 6],
        [9, 2]])


In [55]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[85, 46],
        [81, 50]])

In [57]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)
# transpose (which matrix, konse dimension ko kisse swap)
torch.transpose(f, 0, 1)

tensor([[2, 2],
        [4, 5],
        [7, 6]])

In [58]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 1., 0.],
        [2., 1., 2.],
        [7., 9., 2.]])

In [59]:
# determinant
torch.det(h)

tensor(-38.)

In [60]:
# inverse
torch.inverse(h)

tensor([[ 0.4211,  0.0526, -0.0526],
        [-0.2632, -0.1579,  0.1579],
        [-0.2895,  0.5263, -0.0263]])

5. Comparison Operations

In [61]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[4, 6, 6],
        [8, 4, 9]])
tensor([[0, 7, 9],
        [2, 7, 0]])


In [62]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

6. Special Functions

In [73]:
k=torch.randint(size=(2,3), low=0, high=10 , dtype=torch.float32)
k

tensor([[6., 7., 8.],
        [1., 2., 3.]])

In [74]:
#log
torch.log(k)

tensor([[1.7918, 1.9459, 2.0794],
        [0.0000, 0.6931, 1.0986]])

In [75]:
# exp
torch.exp(k)

tensor([[4.0343e+02, 1.0966e+03, 2.9810e+03],
        [2.7183e+00, 7.3891e+00, 2.0086e+01]])

In [76]:
# sqrt
torch.sqrt(k)

tensor([[2.4495, 2.6458, 2.8284],
        [1.0000, 1.4142, 1.7321]])

In [77]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9991, 0.9997],
        [0.7311, 0.8808, 0.9526]])

In [78]:
#softmax
#relu

# Inplace Operations

In [85]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

# '_' represents inplace operation for permanent change in that tensor rather than occupying more space as new tensor

tensor([[0.7819, 0.3134, 0.2983],
        [0.3436, 0.2028, 0.9792]])
tensor([[0.4947, 0.3617, 0.9687],
        [0.0359, 0.3041, 0.9867]])


In [86]:
m.add_(n)

tensor([[1.2766, 0.6751, 1.2670],
        [0.3795, 0.5069, 1.9659]])

In [87]:
m

tensor([[1.2766, 0.6751, 1.2670],
        [0.3795, 0.5069, 1.9659]])

In [88]:
n

tensor([[0.4947, 0.3617, 0.9687],
        [0.0359, 0.3041, 0.9867]])

In [89]:
n.relu_()

tensor([[0.4947, 0.3617, 0.9687],
        [0.0359, 0.3041, 0.9867]])

# Copying a Tensor

In [90]:
a = torch.rand(2,3)
a

tensor([[0.1290, 0.6887, 0.1637],
        [0.0899, 0.3139, 0.1219]])

In [93]:
#problem with this is that any changes in a will apply in b also that we do not need
b=a

In [94]:
b

tensor([[0.1290, 0.6887, 0.1637],
        [0.0899, 0.3139, 0.1219]])

In [95]:
a[0][0]=0
a

tensor([[0.0000, 0.6887, 0.1637],
        [0.0899, 0.3139, 0.1219]])

In [96]:
b

tensor([[0.0000, 0.6887, 0.1637],
        [0.0899, 0.3139, 0.1219]])

In [97]:
id(a)

132250561149456

In [98]:
id(b)

132250561149456

In [99]:
b=a.clone

In [100]:
id(a)

132250561149456

In [101]:
id(b)

132250570581040