In [ ]:
import torch
print(torch.__version__)

In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available.Using CPU")

# Creating a Tensor


In [ ]:
#using empty
a=torch.empty(2,3)
print(a)

In [8]:
#check type
type(a)

torch.Tensor

In [9]:
#using zeros
b=torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
#using rand (random between 0 to 1)
torch.rand(2,3)

tensor([[0.1723, 0.2704, 0.5821],
        [0.8173, 0.0259, 0.4445]])

In [12]:
#using manual seed (to not change value at evry rand call)
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# other ways

# arange (range)
print("using arange ->", torch.arange(0,10))
print("using arange ->", torch.arange(0,10,2))


# using linspace (linear space from 0 to 10 with 10 elements)
print("using linspace ->", torch.linspace(0,10,10))

# using eye (identity matrix)
print("using eye ->", torch.eye(5))

# using full (3x3 matrix with all elements 5)
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
